### PR TITLE
Make keybindings customizable

### PR DESCRIPTION
**Pull request by techhazard**
This makes it possible to add custom keybindings instead of the hardcoded `Space`, `j` and `k`

I use `Space` as my leader key, but I still want to try this out for a while

Adds a toggle to disable the default keybindings.
Adds some code to make it possible to add custom keybindings
Update Readme with an example of custom keybindings

### CODE REVIEW

**Comment by hoelzro** [comment]
@awesomefireduck Thanks! One small note: you `unmap` j/k/Esc if using the default mappings when exiting split navigate mode, but you never map your custom keybindings when entering split mode.  Is it your intent to always have the split navigation keybindings active, even when not in the custom mode?  I don't know if the plugin will work well that way, but we can work together to make this thing more customizable!

**Comment by techhazard** [comment]
@hoelzro The current implementation of the custom keybindings is indeed very crude.
The move up/down keybindings are currently always mapped.
I tried to put it in a variable, but could not get that to work fast, so I used this as a crude solution to be improved upon.

It would, of course, be nice to have something like the following:

``` vimL
if ! exists("g:splitnavigate_move_up")
  let g:splitnavigate_move_up = 'k'
endif

function! s:ResetSeekBindings()
  [...]
  unmap <buffer> g:splitnavigate_move_up
endfunction

function! s:SetupSeekBindings()
  [...]
  map <buffer> <silent> g:splitnavigate_move_up :call <SID>SelectUpper()<CR>
endfunction

```

**Comment by hoelzro** [comment]
@awesomefireduck I could get that to work, but I won't be able to touch it until tonight my time.  If that's ok with you and you want to try the plugin before I get around to fixing it up, you could always hardcode your own keybindings in the plugin for the time being.

**Comment by techhazard** [comment]
I'm using my branch for now :-)

I need to get back to work, I might have time this weekend to look into making this more robust.

These might help:
http://vim.wikia.com/wiki/Mapping_keys_in_Vim_-_Tutorial_(Part_3)#Use_of_.3CPlug.3E
https://github.com/scrooloose/nerdtree/blob/master/lib/nerdtree/key_map.vim

**Comment by hoelzro** [comment]
Thanks for the feedback - I really need to learn how to use Plug mappings.  I've just used `:execute` to build up custom mappings in the past =/

**Comment by techhazard** [comment]
I've learned a lot by doing this (^^,).

Perhaps the `<Plug>`-way is better, but this works just as good, I think

**Comment by hoelzro** [comment]
Looks great! Thanks for taking the time to do this!

**Pull request merged**
